on: push

jobs:
  ci-back-end:
    name: Build and test back-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.ci.back-end.yml up --build --exit-code-from back-end
